version: '3.8'

services:
  postgres:
    image: postgres:14.3-alpine
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
